version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      service_1:
        condition: service_healthy
      service_2:
        condition: service_healthy
    networks:
      - app-network

  service_1:
    build: ./service_1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  service_2:
    build: ./service_2
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
